name: Project Board Automation

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  project_board_automation:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Move Issue to Project Board
      run: node .github/actions/project-board-automation/move-to-project-board.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
